version: '3'
services:
  bof:
    build: ./bof
    volumes:
      - ./bof/share:/home/bof:ro
      - ./bof/xinetd:/etc/xinetd.d/bof:ro
    ports:
      - "10000:10005"
  ret2code:
    build: ./ret2code
    volumes:
      - ./ret2code/share:/home/ret2code:ro
      - ./ret2code/xinetd:/etc/xinetd.d/ret2code:ro
    ports:
      - "10001:10005"
  got:
    build: ./got
    volumes:
      - ./got/share:/home/got:ro
      - ./got/xinetd:/etc/xinetd.d/got:ro
    ports:
      - "10002:10005"
  ret2sc:
    build: ./ret2sc
    volumes:
      - ./ret2sc/share:/home/ret2sc:ro
      - ./ret2sc/xinetd:/etc/xinetd.d/ret2sc:ro
    ports:
      - "10003:10005"
  rop:
    build: ./rop
    volumes:
      - ./rop/share:/home/rop:ro
      - ./rop/xinetd:/etc/xinetd.d/rop:ro
    ports:
      - "10004:10005"
